services:
  db:
    image: postgres:13
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "devlo"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "Passw0rd"
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d devlo"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - devlo

volumes:
  postgres_data:

networks:
  devlo:
    name: devlo
