"""added user_id

Revision ID: 013783c5db0e
Revises: abe7bcbeda2a
Create Date: 2025-06-17 19:37:27.033689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '013783c5db0e'
down_revision: Union[str, None] = 'abe7bcbeda2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('user_id', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'user_id')
    # ### end Alembic commands ###
