"""added first_name, last_name, phone_number to address

Revision ID: 0ff388f3af0e
Revises: d0a76d3e78a2
Create Date: 2025-07-24 02:07:38.383705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff388f3af0e'
down_revision: Union[str, None] = 'd0a76d3e78a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column('addresses', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.add_column('addresses', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('addresses', 'phone_number')
    op.drop_column('addresses', 'last_name')
    op.drop_column('addresses', 'first_name')
    # ### end Alembic commands ###
