"""added addresses to customer

Revision ID: 64ac9d2b46ac
Revises: 0fbc4abdd0d1
Create Date: 2025-07-24 00:44:03.739727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64ac9d2b46ac'
down_revision: Union[str, None] = '0fbc4abdd0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'addresses', ['id'])
    op.create_unique_constraint(None, 'customers', ['id'])
    op.create_unique_constraint(None, 'orders', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_constraint(None, 'addresses', type_='unique')
    # ### end Alembic commands ###
