"""new tables: Customer, Address

Revision ID: 7f9ccf8edcd3
Revises: f1172838e241
Create Date: 2025-06-15 20:53:17.907542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9ccf8edcd3'
down_revision: Union[str, None] = 'f1172838e241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.drop_table('tenants')
    op.add_column('addresses', sa.Column('address_line_1', sa.String(length=255), nullable=False))
    op.add_column('addresses', sa.Column('address_line_2', sa.String(length=255), nullable=True))
    op.add_column('addresses', sa.Column('postcode', sa.String(length=7), nullable=False))
    op.add_column('addresses', sa.Column('delivery_instructions', sa.String(length=500), nullable=True))
    op.drop_column('addresses', 'street')
    op.drop_column('addresses', 'post_code')
    op.add_column('orders', sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('picked_up_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('orders', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint('orders_delivery_address_id_fkey', 'orders', type_='foreignkey')
    op.drop_column('orders', 'delivery_address_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_address_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('orders_delivery_address_id_fkey', 'orders', 'addresses', ['delivery_address_id'], ['id'])
    op.drop_column('orders', 'updated_at')
    op.drop_column('orders', 'created_at')
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'picked_up_at')
    op.drop_column('orders', 'scheduled_time')
    op.add_column('addresses', sa.Column('post_code', sa.VARCHAR(length=7), autoincrement=False, nullable=False))
    op.add_column('addresses', sa.Column('street', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('addresses', 'delivery_instructions')
    op.drop_column('addresses', 'postcode')
    op.drop_column('addresses', 'address_line_2')
    op.drop_column('addresses', 'address_line_1')
    op.create_table('tenants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tenants_pkey'),
    sa.UniqueConstraint('description', name='tenants_description_key'),
    sa.UniqueConstraint('name', name='tenants_name_key')
    )
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
