""".

Revision ID: 8314a80b3475
Revises: 39f40a3c50b1
Create Date: 2025-06-17 19:03:25.605506

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8314a80b3475"
down_revision: Union[str, None] = "39f40a3c50b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("customers", "phone_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("customers", sa.Column("phone_number", sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
