"""chnaged pickup_address_id to delivery_address_id

Revision ID: c209b537d803
Revises: ca10f5f617c0
Create Date: 2025-06-19 01:47:13.531544

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c209b537d803"
down_revision: Union[str, None] = "ca10f5f617c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
