"""added pickup_address_id and delivery_address_id to Order

Revision ID: df9e40be3a75
Revises: 7f9ccf8edcd3
Create Date: 2025-06-15 20:58:20.844700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df9e40be3a75'
down_revision: Union[str, None] = '7f9ccf8edcd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenants')
    op.add_column('orders', sa.Column('pickup_address_id', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('delivery_address_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'addresses', ['delivery_address_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'addresses', ['pickup_address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'delivery_address_id')
    op.drop_column('orders', 'pickup_address_id')
    op.create_table('tenants',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tenants_pkey'),
    sa.UniqueConstraint('description', name='tenants_description_key'),
    sa.UniqueConstraint('name', name='tenants_name_key')
    )
    # ### end Alembic commands ###
